use_frameworks!

platform :ios, '9.0'

target 'BWANRManage_Example' do
  use_frameworks!
  pod 'BWANRManage', :path => '../'

  target 'BWANRManage_Tests' do
    inherit! :search_paths

    
  end
end
